export const reverse_models = [
  { "id": 1, "model": "gpt-4o-mini", "providers": 5, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 2, "model": "gpt-4o", "providers": 5, "token": "8k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 3, "model": "gpt-4o-all-re", "providers": 1, "token": "8k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 4, "model": "gpt-4o-all-lite-re", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 5, "model": "gpt-4o-vision", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 6, "model": "gpt-3.5-turbo", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 7, "model": "gpt-3.5-turbo-16k", "providers": 1, "token": "16k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 8, "model": "net-gpt-4o-mini", "providers": 1, "token": "8k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 9, "model": "grok-v2", "providers": 1, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 10, "model": "grok-3-office-re", "providers": 1, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 11, "model": "grok-2-1212", "providers": 1, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 12, "model": "gemini-2.0-flash-exp", "providers": 3, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 13, "model": "gemini-2.0-flash-thinking-exp", "providers": 2, "token": "1000k", "features": ["conversation", "internet", "code", "thinking"], "auth": "无需" },
  { "id": 14, "model": "gemini-1.5-flash", "providers": 3, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 15, "model": "gemini-2.0-flash-re", "providers": 1, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 16, "model": "gemini-1.5-pro", "providers": 3, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 17, "model": "gemini-pro", "providers": 2, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 18, "model": "gemini-1.5-flash-vision", "providers": 1, "token": "1000k", "features": ["conversation", "internet", "code"], "auth": "无需" },
  { "id": 19, "model": "claude-3.5-sonnet", "providers": 4, "token": "200k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 20, "model": "claude-3.7-sonnet", "providers": 2, "token": "200k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 21, "model": "claude-3.5-sonnet-poe", "providers": 1, "token": "200k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 22, "model": "claude-3.5-haiku", "providers": 2, "token": "200k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 23, "model": "claude-3.5-sonnet-20241022", "providers": 1, "token": "200k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 24, "model": "deepseek-r1", "providers": 4, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 25, "model": "deepseek-v3", "providers": 5, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 26, "model": "deepseek-reasoner", "providers": 1, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 27, "model": "deepseek-v3-0324", "providers": 1, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 28, "model": "llama-3.3-70b", "providers": 3, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 29, "model": "llama-3.1-405b", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 30, "model": "llama-3.2-3b", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 31, "model": "llama-3.1-8b", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 32, "model": "llama-3.3-70B", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 33, "model": "qwen-2-72b", "providers": 2, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 34, "model": "qwen-coder-32b", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 35, "model": "qwen-2.5-72b-instruct", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 36, "model": "qwen-qwq-32b-preview", "providers": 1, "token": "100k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 37, "model": "QwQ-32B-Preview", "providers": 2, "token": "100k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 38, "model": "qwq-32B-Preview", "providers": 1, "token": "100k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 39, "model": "QWQ-32b-preview", "providers": 1, "token": "100k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 40, "model": "mistral-7b", "providers": 2, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 41, "model": "mistral-nemo", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 42, "model": "mistral-large-2411", "providers": 1, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 43, "model": "mixtral-8x7b", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 44, "model": "sdxl-turbo", "providers": 1, "token": "0.8k", "features": ["drawing"], "auth": "无需" },
  { "id": 45, "model": "o3-mini", "providers": 2, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 46, "model": "yi-lightning", "providers": 2, "token": "16k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 47, "model": "hunyuan-lite", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 48, "model": "glm-4-flash", "providers": 1, "token": "8k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 49, "model": "spark-max", "providers": 1, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 50, "model": "ERNIE-Speed-128k", "providers": 1, "token": "128k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 51, "model": "o1-preview", "providers": 2, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 52, "model": "o1-mini", "providers": 1, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 53, "model": "o1", "providers": 1, "token": "128k", "features": ["conversation", "code", "thinking"], "auth": "无需" },
  { "id": 54, "model": "flux-sch", "providers": 1, "token": "0.8k", "features": ["drawing"], "auth": "无需" },
  { "id": 55, "model": "gemma-2-9b-it", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 56, "model": "glm-4-9b-chat", "providers": 1, "token": "32k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 57, "model": "gemma-3-27b-it", "providers": 1, "token": "64k", "features": ["conversation", "code"], "auth": "无需" },
  { "id": 58, "model": "llama-4-scout", "providers": 1, "token": "1000k", "features": ["conversation", "code"], "auth": "无需" },
];