import { FreeStableDiffusion_1 } from './utils/FreeStableDiffusion/SD_1';
import { FreeDalle_1 } from './utils/Dall-e-3/dalle_1';
import { handleGLM4Completions } from './components/GLM4';
import { handleGLM4VCompletions } from './components/GLM4V';
import { handleTTSCompletions } from './components/TTS';
import { handleChat40Completions } from './components/Chat40';
import { handleChat35Completions } from './components/Chat35';
import { handleGeminiCompletions } from './components/Gemini';
import { handleClaudeCompletions } from './components/Claude';
import { handleSearchCompletions } from './components/Search';
import { handleMoonshotCompletions } from './components/Moonshot';
import { handleSDCompletions } from './components/SD';
import { handleDalleCompletions } from './components/dalle';
import { chatglm4v } from './utils/ChatGLM4/GLM4V';
import { chatglm4 } from './utils/ChatGLM4/GLM4';
import { FreeChat35_1 } from './utils/FreeChat35/chat35_1';
import { FreeChat35_2 } from './utils/FreeChat35/chat35_2';
import { FreeChat35_3 } from './utils/FreeChat35/chat35_3';
import { FreeChat35_4 } from './utils/FreeChat35/chat35_4';
import { FreeChat35_5 } from './utils/FreeChat35/chat35_5';
import { FreeChat35_6 } from './utils/FreeChat35/chat35_6';
import { FreeGemini_1 } from './utils/FreeGemini/Gemini_1';
import { FreeGemini_2 } from './utils/FreeGemini/Gemini_2';
import { FreeGemini_3 } from './utils/FreeGemini/Gemini_3';
import { FreeClaude_1 } from './utils/FreeClaude/Claude_1';
import { FreeSearch_1 } from './utils/FreeSearch/Search_1';
import { FreeErnie_1 } from './utils/FreeErnie/Ernie_1';
import { FreeKimi_1 } from './utils/FreeMoonshot/Kimi_1';
import { FreeChat40_1 } from './utils/FreeChat40/chat_1';
import { FreeChat40_2 } from './utils/FreeChat40/chat_2';
import { FreeChat40_3 } from './utils/FreeChat40/chat_3';
import { FreeChat40_4 } from './utils/FreeChat40/chat_4';
import { FreeChat40_5 } from './utils/FreeChat40/chat_5';
import { getAudioFromTPS_1 } from './utils/TTS/tts_1';

function initializeDependencies(): void {
  FreeStableDiffusion_1();
  FreeDalle_1();
  handleGLM4Completions();
  handleGLM4VCompletions();
  handleTTSCompletions();
  handleChat40Completions();
  handleChat35Completions();
  handleGeminiCompletions();
  handleClaudeCompletions();
  handleSearchCompletions();
  handleMoonshotCompletions();
  handleSDCompletions();
  handleDalleCompletions();
  chatglm4v();
  chatglm4();
  FreeChat35_1();
  FreeChat35_2();
  FreeChat35_3();
  FreeChat35_4();
  FreeChat35_5();
  FreeChat35_6();
  FreeGemini_1();
  FreeGemini_2();
  FreeGemini_3();
  FreeClaude_1();
  FreeSearch_1();
  FreeErnie_1();
  FreeKimi_1();
  FreeChat40_1();
  FreeChat40_2();
  FreeChat40_3();
  FreeChat40_4();
  FreeChat40_5();
  getAudioFromTPS_1();
}

export default initializeDependencies;